"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isValidBST(self, root: Optional[TreeNode]) -> bool:
        def BFS(node, left, right):
            if not node:
                return True
            if not (node.val < right and node.val > left):
                return False
            return (BFS(node.left, left, node.val) and BFS(node.right, node.val, right))
        return BFS(root, float("-inf"), float("inf"))