"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def evalRPN(self, tokens: List[str]) -> int:
        stack = []
        operators = ["+", "-", "*", "/"]

        for toke in tokens:
            try:
                float(toke)
                stack.append(toke)
            except:
                if toke in operators:
                    y = int(stack.pop())
                    x = int(stack.pop())
                    if toke == "+":
                        z = x + y
                    elif toke == "-":
                        z = x - y
                    elif toke == "*":
                        z = x * y
                    else:
                        z = int(x / y)
                    stack.append(z)
        return stack[0]