"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def evalRPN(self, tokens: List[str]) -> int:
        stack = []
        for t in tokens:
            if t in '+-*/':
                y,x = stack.pop(), stack.pop()
                if t == '+':
                    stack.append(x + y)
                elif t == '-':
                    stack.append(x - y)
                elif t == '*':
                    stack.append(x * y)
                else:
                    stack.append(int(x/y))
            else:
                stack.append(int(t))
        return stack[0]