"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def productExceptSelf(self, nums: List[int]) -> List[int]:
        # init result array * len of nums to 1
        res = [1] * len(nums)
        print(res)
        pre = 1
        for i in range(len(nums)):
            res[i] = pre
            pre *= nums[i]
        print(res)
        post = 1
        for i in range(len(nums)-1, -1, -1):
            res[i] *= post
            post *= nums[i]
        print(res)
        return(res)