"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:
        resList = []
        myHeap = []
        if k == len(points):
            return points
        for point in points:
            ed = (point[0]**2 + point[1]**2)
            heapq.heappush(myHeap, [ed, point])
        for i in range(k):
            resList.append(heapq.heappop(myHeap)[1])
        return resList