"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

from collections import deque

class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        hashset = set()
        q = deque()
        longest = 0
        counter = 0 
        for char in s: 
            curr = ''
            if char in hashset:
                while curr != char:
                    curr = q.popleft()
                    counter -= 1
                    hashset.remove(curr)
            q.append(char)
            hashset.add(char)
            counter += 1
            if counter > longest:
                longest = counter
        return longest
