"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

from collections import Counter

class Solution:
    def longestPalindrome(self, s: str) -> int:
        freq = Counter(s)
        result = 0
        odds = False
        for num in freq.values():
            if num % 2:
                odds = True
            result += num - num % 2
        if odds:
            result += 1
        return result