"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def updateMatrix(self, mat: List[List[int]]) -> List[List[int]]:
        m = len(mat)
        n = len(mat[0])
        ans = [[0] * n for _ in range(m)]
        directions = [(0, 1), (0, -1), (1, 0), (-1, 0)]
        visited = set()
        q = deque()

        for i in range(m):
            for j in range(n):
                if mat[i][j] == 0:
                    q.append((i, j))
                    visited.add((i, j))
        dist = 0
        while q:
            for _ in range(len(q)):
                i, j = q.popleft()
                if mat[i][j] == 1:
                    ans[i][j] = dist
            
                for d in directions:
                    new_i = i + d[0]
                    new_j = j + d[1]
                    if 0 <= new_i < m and 0 <= new_j < n and (new_i, new_j) not in visited:
                        visited.add((new_i, new_j))
                        q.append((new_i, new_j))
            dist += 1
        return ans
        
