"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        maxSub = nums[0] #so if it's negative you're not sol
        counter = 0 
        for num in nums:
            counter += num
            maxSub = max(counter, maxSub) #so the next line works when negative
            if counter < 0:
                counter = 0
        return maxSub
    


