"""
Code generated by https://github.com/goodstudyqaq/leetcode-local-tester
"""
try:
    from utils.python3.help import *
except ImportError:
    pass # In leetcode environment, we don't need to import the help file.

class Solution:
    def coinChange(self, coins: List[int], amount: int) -> int:
        # initialize array to amount + 1 * amount + 1
        # base case
        # loop through amounts
        # loop through coins
        # if >= 0: dp[a] = min(dp[a], dp[a -c] + 1)
        # return dp amount if
        dp = [amount + 1] * (amount + 1)
        dp[0] = 0

        for a in range(amount + 1):
            for c in coins:
                if a - c >= 0:
                    dp[a] = min(dp[a], dp[a -c] + 1)
        return dp[amount] if dp[amount] != (amount + 1) else -1